### ISSUE TITLE
为什么我拿ncnn编译出来的.a文件编译so的时候会报类型转换错误？

### ISSUE THREAD

**Issue by h3clikejava** [dangbo/ncnn-mobile#10]
/Users/XXX/Downloads/squeezencnn-AH/app/src/main/jni/squeezencnn_jni.cpp:149:42: error: invalid conversion from 'void*' to 'const float*' [-fpermissive]
             const float* prob = out.data + out.cstep * j;
                                          ^

这里的out.data是void*类型 ，如果强行转换为float*之后虽然可以编译成功，但是最后运行结果不对。

**Comment by cxy200927099** [comment]
兄弟，你这个怎么解决的？怎么issue突然关闭了，也没有说咋解决的？能分享下吗？强制转换不可以？
@h3clikejava @dangbo

**Comment by cxy200927099** [comment]
找到解决方案了，作者在两个地方提了issue，解决了要善于分享啊，这样也方便后人好查看！你说呢，哈哈
参照：[https://github.com/Tencent/ncnn/issues/256](url)
链接跳转不过去，可以复制链接，浏览器重新打开即可
