### ISSUE TITLE
安卓端时间？

### ISSUE THREAD

**Issue by moli232777144** [dangbo/ncnn-mobile#2]
您测试安卓端单次预测的时间是？

**Comment by dangbo** [comment]
170-250ms

**Comment by moli232777144** [comment]
顺便问下，您测试的机子主频是？官方给的测试手机是nexus6p，android7.1.2。测试squeezenet模型，单线程197ms，多线程79ms。您复现的效果比较好，之前跟朋友讨论，都没编译出这个速度。

**Comment by dangbo** [comment]
不好意思，给您造成了困扰。80-100ms是我用 tf 的 mobilenet 的结果，记错了。
